fix missing Python.h
[91mpython/caffe/_caffe.cpp:1:52: fatal error: Python.h: No such file or directory
the solution based on https://groups.google.com/forum/#!topic/caffe-users/2pvE3NgcXJo