fix hdf5
src/caffe/net.cpp:8:18: fatal error: hdf5.h: No such file or directory
cannot find hdf5.h because its located at /usr/lib/x86_64-linux-gnu/hdf5/serial/